### ISSUE TITLE
ux: Config ergonomics for providers vs model overrides

### ISSUE THREAD

**Issue by shazow** [shazow/modelplex#41]
Goals (in order of importance):
1. Support many providers for many models under one endpoint, like a local openrouter
2. Support overriding which models are served (maybe v2 but IMO important to design for)

Right now we have:

```toml
# AI Model Providers
[[providers]]
name = "openai"
type = "openai"
base_url = "https://api.openai.com/v1"
api_key = "${OPENAI_API_KEY}"
models = ["gpt-4", "gpt-3.5-turbo"]
priority = 1
```

We're mapping providers[].models where the models are registered names that map back to the provider, such that if I call a request for "gpt-4" it'll know to use "openai" provider.

To me, I want each provider to default report all of the models it supports. It's not obvious to me what the benefit is to have an allowlist, especially with no overrides? We already achieve goal 1 without the models field?

I was imagining something like...

```toml
[[provider]]
name = "openai"
#...

[[provider]]
name = "openrouter"
#...

[[model]]
name = "gpt-4"
providers = [ "openrouter" ] # Only serve from openrouter!

[[model]]
name = "sonnet-4"
override = "gpt-4" # Inject "sonnet-4" model as supported but actually use "gpt-4" behind the scenes
providers = [ "openai" ] # Only use openai!
```

If no model override is given, then each provider will just register/use whatever models they support. Modelplex will run `/models` to get the list of supported models (on first query?) to figure out the full set of supported models. (Should modelplex auto-update the supported models per-provider anytime /models is loaded? That'd be nice.)
